apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
  namespace: app
  labels:
    app: greetings
  annotations:
    configmap.reloader.stakater.com/reload: "app/hackathon"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
      - name: greeting-message
        image: arunsonti/hello-world-springboot-app:2.0
        envFrom:
          - configMapRef:
              name: hackathon
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
